### ISSUE TITLE
how to create mask.png?

### ISSUE THREAD

**Issue by NerminSalem** [leehomyc/High-Res-Neural-Inpainting#10]
hi, how can i change the mask location used in blend,lua?
ex: i want to make the square mask to mask the top left of the image instead of the center?
can u help

**Comment by kennylovesfree** [comment]
Same question here. Thanks for author's help

**Comment by leehomyc** [comment]
I created it manually. But the context encoder can only inpaints the center of the image. I would suggest move the top left of the image to the center (by padding).

**Comment by NerminSalem** [comment]
thanks alot
