### ISSUE TITLE
Does texture network contain holistic content constraint?

### ISSUE THREAD

**Issue by hhwhbf** [leehomyc/High-Res-Neural-Inpainting#13]
Hi,I have read your new paper,which is clear than the first.
However,through your paper,I found a question.
Does texture network contain holistic content constraint?The content network,which have been trained,contains l2 loss and adversarial loss.But there is an another holistic content constraint in your joint loss function(Equation 1).I don't understand.Is there an extra holistic content constraint in texture network,which is different from the content loss in content network.By the way,does the Equation 1 only belong to the texture network?
Thank you very much.

**Comment by leehomyc** [comment]
The texture network is optimized such that it respects the content of the prediction from the content network, and also respects the texture outside the hole. So basically there are two constraints: one is the prediction from the content network which constraints the global content, the other is the texture from outside the hole which constraints the textures. Is it clear?

**Comment by hhwhbf** [comment]
Yes,from you answer,I can draw a conclusion that the optimization(Equation 1) finished in the texture network.And the content network only provide an object for the texture network.Parameters in content network are invariable when the texture network work.Is that right?

**Comment by leehomyc** [comment]
> Yes,from you answer,I can draw a conclusion that the optimization(Equation 1) finished in the texture network.And the content network only provide an object for the texture network.Parameters in content network are invariable when the texture network work.Is that right?

 You are 100% correct. The content network is fixed and do not change after the first step. It only gives the initial prediction as a constraint to the texture optimization.

**Comment by hhwhbf** [comment]
OK，thank you!
