### ISSUE TITLE
I am not quite sure how you process the multi-scale inpainting.

### ISSUE THREAD

**Issue by Naruto-Sasuke** [leehomyc/High-Res-Neural-Inpainting#18]
Could you give me some description on it ? I don't get the clear descriptions from your paper.

**Comment by leehomyc** [comment]
so in the lowest resolution (128), we run texture network (content = content_network output, texture = 128 image with the hole (we copy paste some contents inside the hole from the boundary). In the second resolution (256), we run texture network again (content = bilinear upsample from texture network output in level 128, texture = 256 image with the hole copy pasted). In the third resolution (512) we run texture network again (content = bilinear upsample from texture network output in level 512, texture = 512 image with hole copy pasted). Think of it as style transfer as every level with initialization at the lower level.

**Comment by Naruto-Sasuke** [comment]
Thank you, It's quite detailed.
