### ISSUE TITLE
Not able to download the content models

### ISSUE THREAD

**Issue by ehsanik** [leehomyc/High-Res-Neural-Inpainting#2]
Apparently the dropbox account you have as a download server in your bash script is suspended. I get this error when I try to run ./models/download_content_models.sh:

`
--2017-02-21 12:30:56--  https://www.dropbox.com/s/skco1wdeeq699z1/imagenet_inpaintCenter.t7?dl=0
Resolving www.dropbox.com (www.dropbox.com)... 162.125.1.1
Connecting to www.dropbox.com (www.dropbox.com)|162.125.1.1|:443... connected.
HTTP request sent, awaiting response... 429 Too Many Requests
2017-02-21 12:30:56 ERROR 429: Too Many Requests.
`

**Comment by leehomyc** [comment]
Sorry for the trouble. I changed it to Google Drive and you can download it there. Please look at the updated README.
