### ISSUE TITLE
Is the model VGG_ILSVRC_19_layers.caffemodel same for any dataset?

### ISSUE THREAD

**Issue by harshithabk** [leehomyc/High-Res-Neural-Inpainting#37]
Hi,  
If we plan to train it with different dataset, then how do we obtain VGG_ILSVRC_19_layers.caffemodel to run    **run_texture_optimization.lua**

**Comment by leehomyc** [comment]
VGG_LISVRC_19 is to extract low-level features. It should be universal for most datasets.

**Comment by harshithabk** [comment]
Thank you so much for the quick response.
